### ISSUE TITLE
Websocket downgrade failure caused by wrong configuration

### ISSUE THREAD

**Issue by pablojan** [P2Pvalue/jetpad#48]
![img_20170308_190923](https://cloud.githubusercontent.com/assets/4454927/23741208/90fae018-04a7-11e7-8e4a-de6a25941f45.jpg)

**Comment by alexseik** [comment]
@pablojan I need more information to reproduce this bug. I can not figure where is it.

**Comment by pablojan** [comment]
This issue is outdated and can't be reproduce as long as SwellRT has changed its transport library.
