### ISSUE TITLE
(Firefox) Ugly look and feel of select elements

### ISSUE THREAD

**Issue by Akronix** [P2Pvalue/jetpad#58]
Here it's how they are displayed in Chromium:
![screenshot from 2017-03-28 10-03-38](https://cloud.githubusercontent.com/assets/2631430/24394843/d8aa309e-139d-11e7-992a-94210a3259a9.png)

And here how they are in Firefox:
![page-shot-2017-3-28 jetpad 1](https://cloud.githubusercontent.com/assets/2631430/24394879/fe43577c-139d-11e7-829f-4b263b62a057.png)

**Comment by pablojan** [comment]
Thanks for your contribution @Akronix ! This issues has been already tracked here #38
